/**
 * This program will calculate how much carbon dioxide (CO2) will
 * be generated by a 2410 gallon gas tank, it reports the amount on CO2 in 
 * both pounds and tons.
 * 
 * @author Max Gordon
 * @version 11/28/19
 */
public class CO2FootprintV2Tester
{
    public static void main(String[] args)
    {
        // Set default size of gas tank
        double gallonsOfGas = 2410;

        // Initialize object
        CO2FootprintV2 footprint = new CO2FootprintV2(gallonsOfGas);

        // Calculates the pounds of CO2 created in pounds then convert it to tons
        footprint.calcTonsCO2();
        footprint.convertTonsToPounds();

        // Print the header to the data
        System.out.println("           CO2 Emissions");
        System.out.println("  Gallons   Pounds      Tons");
        System.out.println("  of Gas   from Gas   from Gas");
        System.out.println("  ****************************");

        // Print the data as formatted by a printf
        System.out.printf("  %6.1f   %8.2f    %6.3f", footprint.getGallons(),
                                                      footprint.getPoundsCO2(),
                                                      footprint.getTonsCO2());

        // Print a blank line to keep everything looking nice
        System.out.println();
    }
}
